# Generated by Django 4.1.3 on 2022-11-24 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student_record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('f_name', models.CharField(max_length=255)),
                ('roll_no', models.CharField(max_length=255)),
            ],
        ),
    ]
