# Generated by Django 4.1.3 on 2023-01-11 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfypapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('html', models.TextField()),
                ('css', models.TextField()),
            ],
        ),
    ]
